version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  userdb:
    image: mysql:latest
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: newpassword
    ports:
      - "5433:3306"  # Expose MySQL on port 5433 on your host
    volumes:
      - mysql-data:/var/lib/mysql  # Corrected volume mapping

networks:
  app-network:
    driver: bridge

volumes:
  elasticsearch-data:
  mysql-data:  # Fixed the volume declaration for MySQL
